### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by ManuelStapper** [ManuelStapper/RandomVariables.jl#4]
- [x] Remove Type Piracy
- [ ] Switch to IntervalSets.jl or Intervals.jl
- [x] Use expectation( ) for (i) expectation of transformed random variables and (ii) fallback for transformations?
- [x] Include forward transformation function in RVtransformed
